name: Cypress and Deployment workflow

on:
  push:
    branches: [ production ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number

  deployment-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the machine and run some commands
        uses: appleboy/ssh-action@master
        with:
          host: 34.217.174.173
          username: magetest
          key:  ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/magetest/webapps/magetest
            git status
            git pull origin production
            echo "After pulling the code"
            git status